import type { Metadata } from "next";
import WagmiProvider from "@/components/Providers/WagmiProvider"
import { NextUIProvider } from "@nextui-org/react";
import Header from "@/components/Header";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <WagmiProvider>
          <NextUIProvider>
            <Header></Header>
            {children}
          </NextUIProvider>
        </WagmiProvider>
      </body>
    </html>
  );
}
